const codegen = (function() {
  const primitives = ['div', 'a', 'p', 'span', 'button', 'input', 'select', 'option', 'textarea'];
  function codegen(model) {
    let code = `// Component generated by chokha
    `;
    code += genImports(model);
    code += genComponent(model);
    return code;
  }

  function genImports(model) {
    return `import { h } from '../vendor/preact.module.js'`;
  }

  function genComponent(model) {
    return `
    export default function({ $model, $dispatch }) {
      return (
        ${render(model)}
      );
    }
    `;
  }

  function render(model) {
    let children = null;
    if (typeof model.children === 'string') {
      children = `'${model.children}'`;
    } else {
      children = model.children.map(child => {
        if (typeof child === 'string') {
          return `'${child}'`;
        } else {
          return render(child)
        }
      })
    }

    let props = '';
    Object.keys(model.props).forEach(key => {
      props += `${key}: "${model.props[key]}",`;
    })

    const componentRef = primitives.includes(model.type) ? `'${model.type}'` : model.type

    return`h(${componentRef},
      {
        ${props}
      },
      [
        ${children}
      ]
    )
    `;
  }

  return codegen;
})();